# Generated by Django 5.0.2 on 2024-02-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='sec_code',
            field=models.CharField(default=12345678, max_length=8),
            preserve_default=False,
        ),
    ]
