# Generated by Django 5.0.2 on 2024-02-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_team_sec_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='code',
            field=models.CharField(default=1234567890, max_length=10),
            preserve_default=False,
        ),
    ]
