# Generated by Django 5.0.2 on 2024-02-20 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_clue_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storyline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='clue',
            name='storyline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.storyline'),
        ),
        migrations.AddField(
            model_name='team',
            name='storyline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.storyline'),
        ),
    ]
