# Generated by Django 5.0.2 on 2024-02-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_userprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
