# Generated by Django 5.0.2 on 2024-02-23 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_team_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clue',
            name='minigame',
        ),
        migrations.AddField(
            model_name='team',
            name='minigame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.minigame'),
        ),
    ]
