# Generated by Django 5.0.2 on 2024-02-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_clue_minigame_team_minigame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='minigame',
        ),
        migrations.AddField(
            model_name='team',
            name='minigames',
            field=models.ManyToManyField(related_name='teams', to='base.minigame'),
        ),
    ]
