# Generated by Django 5.0.2 on 2024-02-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_team_minigame_team_minigames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='minigames',
        ),
        migrations.AddField(
            model_name='team',
            name='hangman',
            field=models.TextField(blank=True, default='not reached', null=True),
        ),
        migrations.DeleteModel(
            name='Minigame',
        ),
    ]
