# Generated by Django 5.0.2 on 2024-02-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_team_minigames_team_hangman_delete_minigame'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='summon',
            field=models.TextField(blank=True, default='not reached', null=True),
        ),
    ]
