# Generated by Django 5.0.2 on 2024-02-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_team_summon'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='betrayal',
            field=models.TextField(blank=True, default='not reached', null=True),
        ),
    ]
