# Generated by Django 5.0.2 on 2024-02-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_team_betrayal'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='color',
            field=models.CharField(blank=True, default='red', null=True),
        ),
    ]
