# Generated by Django 5.0.2 on 2024-02-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_team_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='character',
            field=models.CharField(blank=True, null=True),
        ),
    ]
